// <auto-generated />
using System;
using AtencionesApp.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtencionesApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AtencionesApp.Models.Entities.AtencionEnfermeria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<bool>("Embarazada")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InstitucionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<bool>("SinObraSocial")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TipoAtencion")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstitucionId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AtencionesEnfermeria");
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.AtencionOdontologia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiagnosticoId")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<bool>("Embarazada")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InstitucionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<bool>("SinObraSocial")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TipoConsulta")
                        .HasColumnType("int");

                    b.Property<int>("TipoTurno")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosticoId");

                    b.HasIndex("InstitucionId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AtencionesOdontologia");
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.Diagnostico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Diagnosticos");
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.Institucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoSISA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Dependencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SitioWeb")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipologia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Instituciones");
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Domicilio")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObraSocial")
                        .HasColumnType("longtext");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.PrestacionEnfermeria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtencionId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TipoPrestacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtencionId");

                    b.HasIndex("TipoPrestacionId");

                    b.ToTable("PrestacionesEnfermeria");
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.PrestacionOdontologia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtencionId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TipoPrestacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtencionId");

                    b.HasIndex("TipoPrestacionId");

                    b.ToTable("PrestacionesOdontologia");
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("PuedeCrear")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PuedeEditar")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PuedeEliminar")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PuedeLeer")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Administrador",
                            PuedeCrear = true,
                            PuedeEditar = true,
                            PuedeEliminar = true,
                            PuedeLeer = true
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Director",
                            PuedeCrear = false,
                            PuedeEditar = false,
                            PuedeEliminar = false,
                            PuedeLeer = true
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Enfermero",
                            PuedeCrear = true,
                            PuedeEditar = true,
                            PuedeEliminar = false,
                            PuedeLeer = true
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Odontólogo",
                            PuedeCrear = true,
                            PuedeEditar = true,
                            PuedeEliminar = false,
                            PuedeLeer = true
                        });
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.TipoPrestacionEnfermeria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NombrePrestacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TiposPrestacionEnfermeria");
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.TipoPrestacionOdontologia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NombrePrestacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TiposPrestacionOdontologia");
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.ValoracionDental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtencionOdontologiaId")
                        .HasColumnType("int");

                    b.Property<int>("CariesPerm")
                        .HasColumnType("int");

                    b.Property<int>("CariesTemp")
                        .HasColumnType("int");

                    b.Property<int>("ExtraccionTemp")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ObturadosPerm")
                        .HasColumnType("int");

                    b.Property<int>("ObturadosTemp")
                        .HasColumnType("int");

                    b.Property<int>("PerdidosPerm")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtencionOdontologiaId")
                        .IsUnique();

                    b.ToTable("ValoracionesDentales");
                });

            modelBuilder.Entity("InstitucionUsuario", b =>
                {
                    b.Property<int>("InstitucionesId")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosId")
                        .HasColumnType("int");

                    b.HasKey("InstitucionesId", "UsuariosId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("InstitucionUsuario");
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.AtencionEnfermeria", b =>
                {
                    b.HasOne("AtencionesApp.Models.Entities.Institucion", "Institucion")
                        .WithMany("AtencionesEnfermeria")
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtencionesApp.Models.Entities.Paciente", "Paciente")
                        .WithMany("AtencionesEnfermeria")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtencionesApp.Models.Entities.Usuario", "Usuario")
                        .WithMany("AtencionesEnfermeria")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institucion");

                    b.Navigation("Paciente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.AtencionOdontologia", b =>
                {
                    b.HasOne("AtencionesApp.Models.Entities.Diagnostico", "Diagnostico")
                        .WithMany("AtencionesOdontologia")
                        .HasForeignKey("DiagnosticoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtencionesApp.Models.Entities.Institucion", "Institucion")
                        .WithMany("AtencionesOdontologia")
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtencionesApp.Models.Entities.Paciente", "Paciente")
                        .WithMany("AtencionesOdontologia")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtencionesApp.Models.Entities.Usuario", "Usuario")
                        .WithMany("AtencionesOdontologia")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagnostico");

                    b.Navigation("Institucion");

                    b.Navigation("Paciente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.PrestacionEnfermeria", b =>
                {
                    b.HasOne("AtencionesApp.Models.Entities.AtencionEnfermeria", "Atencion")
                        .WithMany("Prestaciones")
                        .HasForeignKey("AtencionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtencionesApp.Models.Entities.TipoPrestacionEnfermeria", "TipoPrestacion")
                        .WithMany("Prestaciones")
                        .HasForeignKey("TipoPrestacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atencion");

                    b.Navigation("TipoPrestacion");
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.PrestacionOdontologia", b =>
                {
                    b.HasOne("AtencionesApp.Models.Entities.AtencionOdontologia", "Atencion")
                        .WithMany("Prestaciones")
                        .HasForeignKey("AtencionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtencionesApp.Models.Entities.TipoPrestacionOdontologia", "TipoPrestacion")
                        .WithMany("Prestaciones")
                        .HasForeignKey("TipoPrestacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atencion");

                    b.Navigation("TipoPrestacion");
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.Usuario", b =>
                {
                    b.HasOne("AtencionesApp.Models.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.ValoracionDental", b =>
                {
                    b.HasOne("AtencionesApp.Models.Entities.AtencionOdontologia", "AtencionOdontologia")
                        .WithOne("ValoracionDental")
                        .HasForeignKey("AtencionesApp.Models.Entities.ValoracionDental", "AtencionOdontologiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtencionOdontologia");
                });

            modelBuilder.Entity("InstitucionUsuario", b =>
                {
                    b.HasOne("AtencionesApp.Models.Entities.Institucion", null)
                        .WithMany()
                        .HasForeignKey("InstitucionesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtencionesApp.Models.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.AtencionEnfermeria", b =>
                {
                    b.Navigation("Prestaciones");
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.AtencionOdontologia", b =>
                {
                    b.Navigation("Prestaciones");

                    b.Navigation("ValoracionDental");
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.Diagnostico", b =>
                {
                    b.Navigation("AtencionesOdontologia");
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.Institucion", b =>
                {
                    b.Navigation("AtencionesEnfermeria");

                    b.Navigation("AtencionesOdontologia");
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.Paciente", b =>
                {
                    b.Navigation("AtencionesEnfermeria");

                    b.Navigation("AtencionesOdontologia");
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.TipoPrestacionEnfermeria", b =>
                {
                    b.Navigation("Prestaciones");
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.TipoPrestacionOdontologia", b =>
                {
                    b.Navigation("Prestaciones");
                });

            modelBuilder.Entity("AtencionesApp.Models.Entities.Usuario", b =>
                {
                    b.Navigation("AtencionesEnfermeria");

                    b.Navigation("AtencionesOdontologia");
                });
#pragma warning restore 612, 618
        }
    }
}
